site_name: MAGE

exclude_docs: |
    /docs

theme:
    name: material
    language: en

markdown_extensions:
  - nl2br
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - callouts
  - roamlinks
  - search
  - tags
